### ISSUE TITLE
Undeclared dependency on Mojolicious::Lite

### ISSUE THREAD

**Issue by andk** [jberger/Mojolicious-Plugin-SimpleSlides#3]
As per subject. Grep:

http://search.cpan.org/grep?release=Mojolicious-Plugin-SimpleSlides-0.03;string=Mojolicious::Lite;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/67102721

HTH&&Thanks,

**Comment by s1037989** [comment]
Thanks!  Fixed (I hope).
