### ISSUE TITLE
Deprecate this dist

### ISSUE THREAD

**Issue by jberger** [jberger/Mojolicious-Plugin-SimpleSlides#5]
This dist should be deprecated in favor of Mojolicious::Plugin::RevealJS

**Comment by s1037989** [comment]
What is involved in the process of deprecating?

**Comment by jberger** [comment]
Well, indeed finding that out would be part of it. It would at least be notices in the documentation. There is also a new `x_` meta field that indicates deprecation (`x_deprecated` I think). I also would think about transferring it to ADOPTME in case someone else wants it.

Note that the same questions/resolutions apply to https://github.com/jberger/App-MojoSlides/issues/3

**Comment by jberger** [comment]
@s1037989 are you interested in maintaining this dist? If not I'm going to do this. App::MojoSlides has been put down already.

**Comment by s1037989** [comment]
Yeah, go ahead.  I wouldn't be maintaining it for my own sake.  You've been saying for a while now to use other solutions, so I've been doing exactly that!  :D

**Comment by jberger** [comment]
Done
